backend:
  name: github
  repo: rajvirsinghbenipal/hugo-content # Or your test repo
  branch: pre-release
  
  # PKCE Authentication settings for Vercel
  auth_type: pkce
  app_id: Ov23liDQxMotQOnJcxBv # Your GitHub OAuth App Client ID

# A minimal collection for testing
media_folder: "assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}